import Head from 'next/head'
import ArticleCardContainer from '@/components/ArticleCardContainer'
import SearchBar from '@/components/SearchBar'
import useFetch from "../hooks/useFetch";
import { useState, useEffect } from 'react';


export default function Home() {
  //const [data, handleSearch] = useFetch(`https://gnews.io/api/v4/top-headlines?category=general&apikey=48513d43e581f6759ef7e91be18f4bf3`)
  const [searchTerm, setSearchTerm] = useState('')
  const [userInput, setUserInput] = useState('')

  // useEffect(() => {
  //   handleSearch(`https://gnews.io/api/v4/search?q=${}&lang=en&max=2&apikey=48513d43e581f6759ef7e91be18f4bf3`);
  // }, [])

  return (
    <>
      <Head>
        <title>Suzi&apos;s News Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Suzi&apos;s News Website</h1>
        <SearchBar onClick={() => setSearchTerm(userInput)} onChange={(e) => setUserInput(e.target.value)}/>
        <ArticleCardContainer/>
      </main>
    </>
  )
}
