import Head from 'next/head'
import ArticleCardContainer from '@/components/ArticleCardContainer'
import SearchBar from '@/components/SearchBar'
import { useState, useEffect } from 'react';
import {dataType} from "../types";


export default function Home() {
  const [searchTerm, setSearchTerm] = useState<string | null>()
  const [userInput, setUserInput] = useState<string | null>('')
  const [results, setResults] = useState<dataType>();

  useEffect(() => {
    if (searchTerm) {
      fetch(`https://gnews.io/api/v4/search?q=${searchTerm}&lang=en&max=9&apikey=48513d43e581f6759ef7e91be18f4bf3`)
      .then(response => response.json())
      .then(data => setResults(data))}
    else {
      fetch(`https://gnews.io/api/v4/top-headlines?category=general&lang=en&max=9&apikey=48513d43e581f6759ef7e91be18f4bf3`)
      .then(response => response.json())
      .then(data => setResults(data))
    }
  }, [searchTerm])

  return (
    <>
      <Head>
        <title>Suzi&apos;s News Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <img className="logo" src='/SN.png' alt="logo"></img>
        <h1>Suzi&apos;s News Website</h1>
        <SearchBar onClick={() => setSearchTerm(userInput)} onChange={(e) => setUserInput(e.target.value)}/>
        {searchTerm ? <h3>Results related to {searchTerm}:</h3>: <h3>Trending Articles:</h3>}
        {results ? <ArticleCardContainer results={results}/> : <p>Loading...</p>}
      </main>
    </>
  )
}
